using Krackend.Sagas.Orchestrations.Abstractions.Primitives;
using Krackend.Sagas.Orchestrations.Abstractions.Distribution.Security;

namespace Krackend.Sagas.Orchestrations.Runtime.Distribution;

/// <summary>
/// Represents a design/control-plane node trusted by a runtime node for artifact distribution.
/// </summary>
public sealed class RuntimeDesignNode
{
    /// <summary>
    /// Gets or sets the runtime-local design node identifier.
    /// </summary>
    public Id Id { get; set; } = Id.New();

    /// <summary>
    /// Gets or sets the runtime-local key used to identify this design node.
    /// </summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the display name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the design node base URI.
    /// </summary>
    public string EndpointBaseUri { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the runtime node identifier assigned by this design node.
    /// </summary>
    public string RemoteRuntimeNodeId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the distribution mode selected for this connection.
    /// </summary>
    public DistributionConnectionMode DistributionMode { get; set; } = DistributionConnectionMode.HybridSync;

    /// <summary>
    /// Gets or sets token lifetime in seconds for tokens generated by this runtime.
    /// </summary>
    public int AccessTokenTtlSeconds { get; set; } = 86_400;

    /// <summary>
    /// Gets or sets the renewal skew in seconds used before outbound tokens expire.
    /// </summary>
    public int TokenRefreshSkewSeconds { get; set; } = 300;

    /// <summary>
    /// Gets or sets the cache TTL in seconds for positive token validation checks.
    /// </summary>
    public int TokenValidationCacheTtlSeconds { get; set; } = 300;

    /// <summary>
    /// Gets or sets the inbound client id generated by this runtime for Design calls.
    /// </summary>
    public string InboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the inbound credential key id generated by this runtime.
    /// </summary>
    public string InboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the inbound secret hash.
    /// </summary>
    public string InboundSecretHash { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the allowed scopes for inbound calls into this runtime.
    /// </summary>
    public string InboundAllowedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the inbound credential status.
    /// </summary>
    public ConnectionCredentialStatus InboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// Gets or sets when the inbound credential was created.
    /// </summary>
    public DateTime? InboundCredentialCreatedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets when the inbound credential was rotated.
    /// </summary>
    public DateTime? InboundCredentialRotatedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets when the inbound credential was revoked.
    /// </summary>
    public DateTime? InboundCredentialRevokedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets when the last inbound token was issued.
    /// </summary>
    public DateTime? InboundLastTokenIssuedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets when the last inbound token request failed.
    /// </summary>
    public DateTime? InboundLastTokenFailedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets the last inbound token failure reason.
    /// </summary>
    public string InboundLastFailureReason { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the outbound client id imported from Design.
    /// </summary>
    public string OutboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the outbound credential key id imported from Design.
    /// </summary>
    public string OutboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the protected outbound secret imported from Design.
    /// </summary>
    public string ProtectedOutboundSecret { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the requested scopes for outbound calls into Design.
    /// </summary>
    public string OutboundRequestedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the outbound credential status.
    /// </summary>
    public ConnectionCredentialStatus OutboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// Gets or sets when the outbound credential was imported.
    /// </summary>
    public DateTime? OutboundCredentialImportedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets when the last outbound token was received.
    /// </summary>
    public DateTime? OutboundLastTokenReceivedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets an optional description.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a value indicating whether this design node can be used by runtime distribution.
    /// </summary>
    public bool IsEnabled { get; set; } = true;

    /// <summary>
    /// Gets or sets when the node was registered.
    /// </summary>
    public DateTime CreatedOnUtc { get; set; }

    /// <summary>
    /// Gets or sets when the node was last updated.
    /// </summary>
    public DateTime UpdatedOnUtc { get; set; }

}
