using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Krackend.Sagas.Orchestrations.ControlPlane.Application.Distribution;
using Krackend.Sagas.Orchestrations.ControlPlane.Distribution.Enums;

namespace Krackend.Sagas.Orchestrations.ControlPlane.WebUI.Distribution.Areas.OrchestratorDistribution.Pages.RuntimeNodes;

public sealed class IndexModel : PageModel
{
    private readonly IRuntimeNodeApplicationService _service;
    private readonly IRuntimeNodeConnectionApplicationService _connectionService;

    public IndexModel(
        IRuntimeNodeApplicationService service,
        IRuntimeNodeConnectionApplicationService connectionService)
    {
        _service = service;
        _connectionService = connectionService;
    }

    public IReadOnlyCollection<RuntimeNodeModel> Rows { get; private set; } = Array.Empty<RuntimeNodeModel>();
    [BindProperty] public RuntimeNodeInput Input { get; set; } = new();
    [BindProperty] public RuntimeNodeCredentialsInput Credentials { get; set; } = new();
    public IReadOnlyCollection<RuntimeNodeDistributionModeOption> DistributionModeOptions { get; } =
    [
        new RuntimeNodeDistributionModeOption
        {
            Value = DistributionMode.DesignPublishesToRuntime.ToString(),
            Label = "Design publishes releases",
            Description = "Design sends approved releases to Runtime using the Runtime credentials."
        },
        new RuntimeNodeDistributionModeOption
        {
            Value = DistributionMode.RuntimeFetchesFromDesign.ToString(),
            Label = "Runtime imports releases",
            Description = "Runtime owners import approved releases using credentials generated by Design."
        },
        new RuntimeNodeDistributionModeOption
        {
            Value = DistributionMode.HybridSync.ToString(),
            Label = "Both directions",
            Description = "Design can publish releases and Runtime can import them manually."
        }
    ];
    public string GeneratedCredentialsJson { get; private set; } = string.Empty;
    public string GeneratedCredentialsNodeName { get; private set; } = string.Empty;

    public async Task OnGetAsync(CancellationToken cancellationToken = default)
    {
        var result = await _service.GetAll(new ApplicationPagedSettings { PageNumber = 1, PageSize = 100 }, cancellationToken);
        Rows = result.Rows;
    }

    public async Task<IActionResult> OnPostUpsertAsync(CancellationToken cancellationToken = default)
    {
        RemoveModelStateBranch(nameof(Credentials));

        if (!ModelState.IsValid)
        {
            await OnGetAsync(cancellationToken);
            return Page();
        }

        await _service.Upsert(new UpsertRuntimeNodeInput(
            Input.RuntimeNodeId,
            Input.Name.Trim(),
            Input.Code.Trim(),
            Input.DistributionMode,
            Input.EndpointBaseUri?.Trim() ?? string.Empty,
            Input.Description?.Trim() ?? string.Empty), cancellationToken);
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSetStatusAsync(string runtimeNodeId, RuntimeNodeStatus status, CancellationToken cancellationToken = default)
    {
        try
        {
            await _service.SetStatus(runtimeNodeId, status, cancellationToken);
            SetMessage("Runtime node updated", $"Runtime node moved to {status}.", "success");
        }
        catch (Exception ex)
        {
            SetMessage("Runtime node update failed", ex.Message, "error");
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteAsync(string runtimeNodeId, CancellationToken cancellationToken = default)
    {
        try
        {
            await _service.Delete(runtimeNodeId, cancellationToken);
            SetMessage("Runtime node deleted", "The runtime node was removed from active configuration.", "success");
        }
        catch (Exception ex)
        {
            SetMessage("Runtime node delete failed", ex.Message, "error");
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostGenerateCredentialsAsync(string runtimeNodeId, CancellationToken cancellationToken = default)
    {
        ModelState.Clear();

        try
        {
            var credentials = await _connectionService.GenerateCredentialPackage(
                runtimeNodeId,
                ResolveCurrentBaseUrl(),
                cancellationToken);
            GeneratedCredentialsJson = credentials.Json;
            SetMessage("Credentials generated", "Copy these credentials now. The secret is shown only in this response.", "success");
        }
        catch (Exception ex)
        {
            SetMessage("Credentials failed", ex.Message, "error");
        }

        await OnGetAsync(cancellationToken);
        GeneratedCredentialsNodeName = Rows.FirstOrDefault(x => x.Id == runtimeNodeId)?.Name ?? "Runtime node";
        return Page();
    }

    public async Task<IActionResult> OnPostImportCredentialsAsync(CancellationToken cancellationToken = default)
    {
        RemoveModelStateBranch(nameof(Input));

        if (string.IsNullOrWhiteSpace(Credentials.RuntimeNodeId) ||
            string.IsNullOrWhiteSpace(Credentials.CredentialsJson))
        {
            ModelState.Clear();
            SetMessage("Credential import failed", "Select a runtime node and provide the credentials JSON.", "error");
            await OnGetAsync(cancellationToken);
            return Page();
        }

        try
        {
            await _connectionService.ImportCredentialPackage(new ImportRuntimeNodeCredentialPackageInput
            {
                RuntimeNodeId = Credentials.RuntimeNodeId,
                Package = Credentials.CredentialsJson
            }, cancellationToken);
            SetMessage("Credential imported", "Design can now request short-lived tokens from the runtime node.", "success");
        }
        catch (Exception ex)
        {
            SetMessage("Credential import failed", ex.Message, "error");
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostValidateConnectionAsync(string runtimeNodeId, CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _connectionService.ValidateConnection(runtimeNodeId, cancellationToken);
            SetMessage(
                result.Succeeded ? "Connection check succeeded" : "Connection check failed",
                result.Message,
                result.Succeeded ? "success" : "error");
        }
        catch (Exception ex)
        {
            SetMessage("Connection check failed", ex.Message, "error");
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostWizardUpsertAsync(CancellationToken cancellationToken = default)
    {
        RemoveModelStateBranch(nameof(Credentials));

        if (!ModelState.IsValid)
        {
            return BadRequest(new { message = BuildModelStateMessage() });
        }

        try
        {
            var runtimeNodeId = await _service.Upsert(new UpsertRuntimeNodeInput(
                Input.RuntimeNodeId,
                Input.Name.Trim(),
                Input.Code.Trim(),
                Input.DistributionMode,
                Input.EndpointBaseUri?.Trim() ?? string.Empty,
                Input.Description?.Trim() ?? string.Empty), cancellationToken);

            return new JsonResult(new
            {
                message = "Policy saved.",
                node = ToClientNode(await GetRuntimeNode(runtimeNodeId, cancellationToken))
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    public async Task<IActionResult> OnPostWizardImportCredentialsAsync(CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(Credentials.RuntimeNodeId) ||
            string.IsNullOrWhiteSpace(Credentials.CredentialsJson))
        {
            return BadRequest(new { message = "Select a runtime node and provide the credentials JSON." });
        }

        try
        {
            await _connectionService.ImportCredentialPackage(new ImportRuntimeNodeCredentialPackageInput
            {
                RuntimeNodeId = Credentials.RuntimeNodeId,
                Package = Credentials.CredentialsJson
            }, cancellationToken);

            return new JsonResult(new
            {
                message = "Credentials imported.",
                node = ToClientNode(await GetRuntimeNode(Credentials.RuntimeNodeId, cancellationToken))
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    public async Task<IActionResult> OnPostWizardGenerateCredentialsAsync(string runtimeNodeId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(runtimeNodeId))
        {
            return BadRequest(new { message = "Select a runtime node." });
        }

        try
        {
            var credentials = await _connectionService.GenerateCredentialPackage(
                runtimeNodeId,
                ResolveCurrentBaseUrl(),
                cancellationToken);

            return new JsonResult(new
            {
                message = "Credentials generated.",
                credentialsJson = credentials.Json,
                node = ToClientNode(await GetRuntimeNode(runtimeNodeId, cancellationToken))
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    public async Task<IActionResult> OnPostWizardValidateConnectionAsync(string runtimeNodeId, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(runtimeNodeId))
        {
            return BadRequest(new { message = "Select a runtime node." });
        }

        try
        {
            var result = await _connectionService.ValidateConnection(runtimeNodeId, cancellationToken);
            return new JsonResult(new
            {
                message = result.Message,
                succeeded = result.Succeeded,
                node = ToClientNode(await GetRuntimeNode(runtimeNodeId, cancellationToken))
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    public async Task<IActionResult> OnPostWizardSetStatusAsync(
        string runtimeNodeId,
        RuntimeNodeStatus status,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(runtimeNodeId))
        {
            return BadRequest(new { message = "Select a runtime node." });
        }

        try
        {
            await _service.SetStatus(runtimeNodeId, status, cancellationToken);
            return new JsonResult(new
            {
                message = $"Runtime node moved to {status}.",
                node = ToClientNode(await GetRuntimeNode(runtimeNodeId, cancellationToken))
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    private string ResolveCurrentBaseUrl()
        => $"{Request.Scheme}://{Request.Host}".TrimEnd('/');

    private void RemoveModelStateBranch(string prefix)
    {
        var keys = ModelState.Keys
            .Where(x => x.Equals(prefix, StringComparison.Ordinal) ||
                        x.StartsWith($"{prefix}.", StringComparison.Ordinal))
            .ToArray();

        foreach (var key in keys)
        {
            ModelState.Remove(key);
        }
    }

    private void SetMessage(string title, string body, string type)
    {
        TempData["OrchestratorMessage.Title"] = title;
        TempData["OrchestratorMessage.Body"] = body;
        TempData["OrchestratorMessage.Type"] = type;
    }

    private async Task<RuntimeNodeModel> GetRuntimeNode(string runtimeNodeId, CancellationToken cancellationToken)
    {
        var result = await _service.GetAll(new ApplicationPagedSettings { PageNumber = 1, PageSize = 500 }, cancellationToken);
        return result.Rows.FirstOrDefault(x => string.Equals(x.Id, runtimeNodeId, StringComparison.Ordinal))
            ?? throw new InvalidOperationException("Runtime node was not found.");
    }

    private string BuildModelStateMessage()
    {
        var errors = ModelState.Values
            .SelectMany(x => x.Errors)
            .Select(x => x.ErrorMessage)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .ToArray();

        return errors.Length == 0
            ? "Review the runtime node capture."
            : string.Join(Environment.NewLine, errors);
    }

    private static object ToClientNode(RuntimeNodeModel node)
        => new
        {
            id = node.Id,
            name = node.Name,
            code = node.Code,
            distributionMode = node.DistributionMode,
            distributionModeLabel = DistributionModeLabel(node.DistributionMode),
            distributionModeDescription = DistributionModeDescription(node.DistributionMode),
            endpointBaseUri = node.EndpointBaseUri,
            endpointApiPath = node.EndpointApiPath,
            status = node.Status,
            statusLabel = ReadableLabel(node.Status),
            inboundCredentialStatus = node.InboundCredentialStatus,
            inboundCredentialStatusLabel = ReadableLabel(node.InboundCredentialStatus),
            outboundCredentialStatus = node.OutboundCredentialStatus,
            outboundCredentialStatusLabel = ReadableLabel(node.OutboundCredentialStatus),
            accessTokenTtlSeconds = node.AccessTokenTtlSeconds.ToString(),
            tokenRefreshSkewSeconds = node.TokenRefreshSkewSeconds.ToString(),
            tokenValidationCacheTtlSeconds = node.TokenValidationCacheTtlSeconds.ToString(),
            inboundClientId = node.InboundClientId,
            inboundKeyId = node.InboundKeyId,
            inboundAllowedScopes = node.InboundAllowedScopes,
            inboundCredentialCreatedAt = DateOrDash(node.InboundCredentialCreatedAtUtc),
            inboundCredentialRotatedAt = DateOrDash(node.InboundCredentialRotatedAtUtc),
            inboundCredentialRevokedAt = DateOrDash(node.InboundCredentialRevokedAtUtc),
            inboundLastTokenIssuedAt = DateOrDash(node.InboundLastTokenIssuedAtUtc),
            inboundLastTokenFailedAt = DateOrDash(node.InboundLastTokenFailedAtUtc),
            inboundLastFailureReason = node.InboundLastFailureReason,
            outboundClientId = node.OutboundClientId,
            outboundKeyId = node.OutboundKeyId,
            outboundRequestedScopes = node.OutboundRequestedScopes,
            outboundCredentialImportedAt = DateOrDash(node.OutboundCredentialImportedAtUtc),
            outboundLastTokenReceivedAt = DateOrDash(node.OutboundLastTokenReceivedAtUtc),
            isEnabled = node.IsEnabled.ToString(),
            isDeleted = node.IsDeleted.ToString(),
            deletedAt = DateOrDash(node.DeletedAtUtc),
            description = node.Description,
            registeredAt = DateOrDash(node.RegisteredAtUtc),
            lastUpdatedAt = DateOrDash(node.LastUpdatedAtUtc)
        };

    private static string DateOrDash(DateTime? value)
        => value.HasValue ? value.Value.ToString("yyyy-MM-dd HH:mm:ss") : "-";

    private static string DateOrDash(DateTime value)
        => value.ToString("yyyy-MM-dd HH:mm:ss");

    private static string DistributionModeLabel(string mode)
        => mode switch
        {
            "DesignPublishesToRuntime" => "Design publishes releases",
            "RuntimeFetchesFromDesign" => "Runtime imports releases",
            "HybridSync" => "Both directions",
            _ => TextOrDash(mode)
        };

    private static string DistributionModeDescription(string mode)
        => mode switch
        {
            "DesignPublishesToRuntime" => "Design sends approved releases to Runtime using the Runtime credentials.",
            "RuntimeFetchesFromDesign" => "Runtime owners import approved releases using credentials generated by Design.",
            "HybridSync" => "Design can publish releases and Runtime can import them manually.",
            _ => string.Empty
        };

    private static string ReadableLabel(string value)
        => value switch
        {
            "NotActivated" => "Not activated",
            "ActivationFailed" => "Activation failed",
            _ => TextOrDash(value)
        };

    private static string TextOrDash(string value)
        => string.IsNullOrWhiteSpace(value) ? "-" : value;
}

