<Project>
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>

    <Authors>Elysium Coding</Authors>
    <Company>Elysium Coding</Company>
    <RepositoryUrl>https://github.com/mape1402/krackend</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/mape1402/krackend</PackageProjectUrl>
    <PackageIcon>image.png</PackageIcon>
    <PackageReleaseNotes>https://github.com/mape1402/krackend/releases</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>krackend;dotnet;event-sourcing;sagas;orchestration</PackageTags>
    <UseRootPackageReadme>true</UseRootPackageReadme>
  </PropertyGroup>

  <PropertyGroup>
    <IsSourceProject Condition="$([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('\src\')) Or $([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('/src/'))">true</IsSourceProject>
    <GenerateDocumentationFile Condition="'$(IsSourceProject)' == 'true'">true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseRootPackageReadme)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)assets/image.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <Version Condition="'$(MinVerVersion)' != ''">$(MinVerVersion)</Version>
    <Version Condition="'$(MinVerVersion)' == ''">1.0.0</Version>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
    <MinVerBuildMetadata>build.{DateTime:yyyyMMddHHmmss}</MinVerBuildMetadata>
    <MinVerIsRelease>false</MinVerIsRelease>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

</Project>
