<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Krackend.EventSourcing.PelicanExtensions</PackageId>
    <Description>Krackend.EventSourcing.PelicanExtensions provides optional integration points between Pelican/template handlers and Krackend event sourcing.</Description>
    <PackageTags>event-sourcing;pelican;template;extensions;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Krackend.EventSourcing\Krackend.EventSourcing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
