<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Inventories.Api\Inventories.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="TurtlePath.Testing" />
    <PackageReference Include="TurtlePath.Testing.EntityFrameworkCore" />
    <PackageReference Include="TurtlePath.Testing.Integration" />
  </ItemGroup>

</Project>
