<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer</PackageId>
    <Description>Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer provides SQL Server persistence adapters for saga orchestration runtimes.</Description>
    <PackageTags>saga;orchestration;entity-framework-core;sql-server;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations\Krackend.Sagas.Orchestrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

</Project>
