// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Infrastructure;

#nullable disable

namespace Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(RuntimeStorageDbContext))]
    partial class RuntimeStorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Runtime")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.CompensationExecutionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CompensationTaskKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SourceTaskExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "SourceTaskExecutionId");

                    b.ToTable("CompensationExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.EnvironmentVariableEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastValidatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VariableKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey", "VariableKey")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.ExecutionTransitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("StageExecutionId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("TaskExecutionAttemptId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("TaskExecutionId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "OccurredOnUtc");

                    b.ToTable("ExecutionTransitions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.InstanceVariableEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "Key")
                        .IsUnique();

                    b.ToTable("InstanceVariables", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.OrchestrationInstanceEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("ActiveLeaseExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActiveLeaseId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompensatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompensationStartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentParallelGroupKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentStageKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentTaskKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExecutionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalOutcome")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RuntimeOrchestrationArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("SnapshotPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("StoppedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TriggerIntakeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ExecutionKey")
                        .IsUnique();

                    b.HasIndex("EnvironmentKey", "Status");

                    b.ToTable("OrchestrationInstances", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.RuntimeArtifactEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("ActivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtifactChecksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArtifactPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("DeployedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LoadedToCache")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("OrchestrationDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RetiredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SourceOrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("SupersededByArtifactId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey", "OrchestrationDefinitionKey", "IsActive");

                    b.HasIndex("EnvironmentKey", "OrchestrationDefinitionKey", "Version", "ArtifactType")
                        .IsUnique();

                    b.ToTable("Artifacts", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.StageExecutionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool?>("ExecutionConditionResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ParallelGroupCount")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("WasSkipped")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "StageKey")
                        .IsUnique();

                    b.ToTable("StageExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.TaskDispatchEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("AcknowledgedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommandId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Destination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TaskExecutionAttemptId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("TaskDispatches", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.TaskExecutionAttemptEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DispatchId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("TaskExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("TimedOutOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaskExecutionId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("TaskExecutionAttempts", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.TaskExecutionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("AwaitResponse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("ExecutionConditionResult")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastAttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("OutputVariablesPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ParallelGroupId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<byte[]>("StageExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TaskKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("TimedOutOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasSkipped")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OrchestrationInstanceId", "TaskKey");

                    b.ToTable("TaskExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.TriggerIntakeAttemptEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("FinishedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TriggerIntakeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("TriggerIntakeId", "AttemptNumber");

                    b.ToTable("TriggerIntakeAttempts", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.Entities.TriggerIntakeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("BufferLocation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersistenceLevel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("PromotedInstanceId")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("PromotedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("ResolvedArtifactId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("SourceMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceRequestId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TriggerKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey", "IdempotencyKey");

                    b.HasIndex("EnvironmentKey", "TriggerKey", "Status");

                    b.ToTable("TriggerIntakes", "Runtime");
                });
#pragma warning restore 612, 618
        }
    }
}
