<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Krackend.Sagas.Orchestrations.Messaging.Pigeon</PackageId>
    <Description>Krackend.Sagas.Orchestrations.Messaging.Pigeon provides the Pigeon messaging adapter for saga orchestration runtimes.</Description>
    <PackageTags>saga;orchestration;messaging;pigeon;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Messaging.Abstractions\Krackend.Sagas.Orchestrations.Messaging.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Mule.DurableActions" Version="1.3.0" />
    <PackageReference Include="Pigeon.Messaging" />
  </ItemGroup>

</Project>
