<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Krackend.Sagas.Orchestrations.Client.Spider</PackageId>
    <Description>Spider pipeline extensions for Krackend orchestration client services.</Description>
    <PackageTags>saga;orchestration;client;spider;dotnet</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pelican.Mediator" Version="2.0.0" />
    <PackageReference Include="Spider.Pipelines" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Client\Krackend.Sagas.Orchestrations.Client.csproj" />
  </ItemGroup>

</Project>
