// <auto-generated />
using System;
using Krackend.Sagas.Orchestrations.Runtime.Storage.EntityFramework.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krackend.Sagas.Orchestrations.RuntimeHost.Sample.Migrations.RuntimeStorage
{
    [DbContext(typeof(RuntimeDbContext))]
    [Migration("20260825074723_AddRuntimeArtifactLifecycle")]
    partial class AddRuntimeArtifactLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Runtime")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.CompensationExecution", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CompensationTaskKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SourceTaskExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId");

                    b.ToTable("CompensationExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.EnvironmentVariableValue", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastValidatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VariableKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey", "VariableKey")
                        .IsUnique();

                    b.ToTable("EnvironmentVariableValues", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.ExecutionTransition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("StageExecutionId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("TaskExecutionAttemptId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("TaskExecutionId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("OrchestrationInstanceId", "OccurredOnUtc");

                    b.ToTable("ExecutionTransitions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.InstanceVariable", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "Key")
                        .IsUnique();

                    b.ToTable("InstanceVariables", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.OrchestrationInstance", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("ActiveLeaseExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActiveLeaseId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompensatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompensationStartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentParallelGroupKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentStageKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentTaskKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExecutionKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalOutcome")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RuntimeOrchestrationArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("SnapshotPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("StoppedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TriggerIntakeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EnvironmentKey", "LastUpdatedOnUtc");

                    b.ToTable("OrchestrationInstances", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.RuntimeOrchestrationArtifact", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("ActivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtifactChecksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArtifactPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("DeployedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("IngressGeneration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LoadedToCache")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrchestrationDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ProjectionCompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectionError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ProjectionFailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProjectionStartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RetiredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SourceOrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Pending");

                    b.Property<byte[]>("SupersededByArtifactId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey", "OrchestrationDefinitionKey", "IsActive");

                    b.HasIndex("EnvironmentKey", "OrchestrationDefinitionKey", "Version")
                        .IsUnique();

                    b.HasIndex("EnvironmentKey", "Status", "IsActive");

                    b.ToTable("RuntimeOrchestrationArtifacts", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.StageExecution", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("ExecutionConditionResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ParallelGroupCount")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("WasSkipped")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationInstanceId", "StageKey")
                        .IsUnique();

                    b.ToTable("StageExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.TaskDispatch", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("AcknowledgedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommandId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Destination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TaskExecutionAttemptId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("DispatchStatus");

                    b.HasIndex("TaskExecutionAttemptId")
                        .IsUnique();

                    b.ToTable("TaskDispatches", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.TaskExecution", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("AwaitResponse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("ExecutionConditionResult")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastAttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("OrchestrationInstanceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("OutputVariablesPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ParallelGroupId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("StageExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TaskKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("TimedOutOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasSkipped")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Status");

                    b.HasIndex("StageExecutionId", "TaskKey")
                        .IsUnique();

                    b.ToTable("TaskExecutions", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Abstractions.Runtime.TaskExecutionAttempt", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DispatchId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("TaskExecutionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("TimedOutOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaitingSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskExecutionId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("TaskExecutionAttempts", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Runtime.Distribution.RuntimeDesignNode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EndpointBaseUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemoteRuntimeNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("RuntimeDesignNodes", "Runtime");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Runtime.Ingress.RuntimeIngressConfiguration", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngressKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IngressTransport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RuntimeOrchestrationArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("SettingsPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "RuntimeOrchestrationArtifactId");

                    b.HasIndex("RuntimeOrchestrationArtifactId", "ConfigurationKey")
                        .IsUnique();

                    b.HasIndex("IsActive", "IngressTransport", "IngressKind");

                    b.ToTable("RuntimeIngressConfigurations", "Runtime");
                });

            modelBuilder.Entity("Mule.DurableAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LockedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextAttemptOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("StartedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("TerminalOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_MuleActions_Key_DeduplicationKey")
                        .HasFilter("[DeduplicationKey] IS NOT NULL");

                    b.HasIndex("Status", "CompletedOnUtc")
                        .HasDatabaseName("IX_MuleActions_Status_CompletedOnUtc");

                    b.HasIndex("Status", "LockedOnUtc")
                        .HasDatabaseName("IX_MuleActions_Status_LockedOnUtc");

                    b.HasIndex("Lane", "Status", "NextAttemptOnUtc", "CreatedOnUtc")
                        .HasDatabaseName("IX_MuleActions_Lane_Status_NextAttemptOnUtc_CreatedOnUtc");

                    b.ToTable("MuleActions", "Runtime");
                });
#pragma warning restore 612, 618
        }
    }
}
