<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1573;CS1574;CS1587;CS1591;NU5104</NoWarn>
    <PackageId>Krackend.Sagas.Orchestrations.Distribution.Interaction</PackageId>
    <Description>Application interaction layer for Krackend saga orchestration distribution workflows.</Description>
    <PackageTags>saga;orchestration;distribution;interaction;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Contracts\Krackend.Sagas.Orchestrations.Contracts.csproj" />
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Design\Krackend.Sagas.Orchestrations.Design.csproj" />
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Distribution\Krackend.Sagas.Orchestrations.Distribution.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
