<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Krackend.Sagas.Orchestrations.Abstractions\Krackend.Sagas.Orchestrations.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer\Krackend.Sagas.Orchestrations.EntityFrameworkCore.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Krackend.Sagas.Orchestrations.Messaging.Abstractions\Krackend.Sagas.Orchestrations.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Krackend.Sagas.Orchestrations\Krackend.Sagas.Orchestrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
