// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Infrastructure;

#nullable disable

namespace Krackend.Sagas.Orchestrations.ControlPlaneHost.Sample.Migrations.DesignStorage
{
    [DbContext(typeof(DesignStorageDbContext))]
    [Migration("20260414192000_InitialDesignStorageSqlServer")]
    partial class InitialDesignStorageSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("FromId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("NavigateToId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("NavigateToType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Condition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity.Condition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.Property<string>("Notes");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity.Condition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("ConditionJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("BranchRuleDefinitions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.OrchestrationDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("OrchestrationDefinitions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.OrchestrationVersionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationDefinitionId");

                    b.HasIndex("OrchestrationDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("OrchestrationVersions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.ParallelGroupDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("MaxParallelAgents")
                        .HasColumnType("int");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("ParallelGroupDefinitions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DefaultOnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DefaultRetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.DefaultRetryPolicy#RetryPolicyJsonModel", b1 =>
                        {
                            b1.Property<int>("MaxRetries");

                            b1.PrimitiveCollection<string>("RetryableErrorCodes");

                            b1.Property<bool>("StopOnNonRetryableError");

                            b1.Property<int>("StrategyType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.DefaultRetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("DefaultRetryPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DefaultTimeoutPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.DefaultTimeoutPolicy#TimeoutPolicyJsonModel", b1 =>
                        {
                            b1.Property<TimeSpan>("Timeout");

                            b1.Property<int>("TimeoutBehavior");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutBehaviorPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.DefaultTimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("DefaultTimeoutPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.Property<string>("Notes");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("ExecutionConditionJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Order");

                    b.ToTable("StageDefinitions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("ParallelGroupId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CompensationDefinition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel", b1 =>
                        {
                            b1.Property<int>("CompensationTaskKind");

                            b1.Property<int>("DispatchType");

                            b1.Property<string>("Notes");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.ExecutionCondition#ExecutionConditionJsonModel", b2 =>
                                {
                                    b2.Property<int>("Engine");

                                    b2.Property<string>("Notes");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.RetryPolicy#RetryPolicyJsonModel", b2 =>
                                {
                                    b2.Property<int>("MaxRetries");

                                    b2.PrimitiveCollection<string>("RetryableErrorCodes");

                                    b2.Property<bool>("StopOnNonRetryableError");

                                    b2.Property<int>("StrategyType");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel", b2 =>
                                {
                                    b2.Property<TimeSpan>("Timeout");

                                    b2.Property<int>("TimeoutBehavior");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutBehaviorPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Transformation", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Transformation#TransformationDefinitionJsonModel", b2 =>
                                {
                                    b2.Property<int>("Engine");

                                    b2.Property<string>("Notes");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("CompensationDefinitionJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationJsonModel", b1 =>
                        {
                            b1.Property<string>("Type")
                                .HasJsonPropertyName("$type");

                            b1.ToJson("ConfigurationJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.Property<string>("Notes");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("ExecutionConditionJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.RetryPolicy#RetryPolicyJsonModel", b1 =>
                        {
                            b1.Property<int>("MaxRetries");

                            b1.PrimitiveCollection<string>("RetryableErrorCodes");

                            b1.Property<bool>("StopOnNonRetryableError");

                            b1.Property<int>("StrategyType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("RetryPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel", b1 =>
                        {
                            b1.Property<TimeSpan>("Timeout");

                            b1.Property<int>("TimeoutBehavior");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutBehaviorPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("TimeoutPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Transformation", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Transformation#TransformationDefinitionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.Property<string>("Notes");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("TransformationJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.HasIndex("StageDefinitionId", "Order");

                    b.ToTable("TaskDefinitions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TriggerChannel", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity.TriggerChannel#TriggerChannelJsonModel", b1 =>
                        {
                            b1.Property<string>("Type")
                                .HasJsonPropertyName("$type");

                            b1.ToJson("TriggerChannelJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.ToTable("TriggerBindings", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.VariableDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Key")
                        .IsUnique();

                    b.ToTable("VariableDefinitions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
