// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Infrastructure;

#nullable disable

namespace Krackend.Sagas.Orchestrations.ControlPlaneHost.Sample.Migrations.DesignStorage
{
    [DbContext(typeof(DesignStorageDbContext))]
    [Migration("20260527034001_AddDomainCatalogAndOrchestrationDomainFk")]
    partial class AddDomainCatalogAndOrchestrationDomainFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Design")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("FromId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("NavigateToId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("NavigateToType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Condition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity.Condition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity.Condition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.BranchRuleDefinitionEntity.Condition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel.Dsl#DslConditionConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Expression");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("ConditionJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("BranchRuleDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.DomainEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Domains", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.OrchestrationDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Domain")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("DomainId")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("OrchestrationDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.OrchestrationVersionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationDefinitionId");

                    b.HasIndex("OrchestrationDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("OrchestrationVersions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.ParallelGroupDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("MaxParallelAgents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("ParallelGroupDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.StageDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel.Dsl#DslConditionConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Expression");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("ExecutionConditionJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Order");

                    b.ToTable("StageDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("ParallelGroupId")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CompensationDefinition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel", b1 =>
                        {
                            b1.Property<int>("CompensationTaskKind");

                            b1.Property<int>("DispatchType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Http", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.Http#HttpTaskConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<bool>("AllowSyncResponse");

                                            b3.Property<string>("BaseUrlVariableRef");

                                            b3.PrimitiveCollection<string>("ExpectedStatusCodes");

                                            b3.Property<string>("HeadersTemplateJson");

                                            b3.Property<string>("Method");

                                            b3.Property<string>("QueryTemplateJson");

                                            b3.Property<string>("RelativePath");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "SchemaBinding", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.Http#HttpTaskConfigurationJsonModel.SchemaBinding#SchemaBindingJsonModel", b4 =>
                                                {
                                                    b4.Property<string>("ContractId");

                                                    b4.Property<string>("ContractKey");

                                                    b4.Property<string>("ContractVersion");

                                                    b4.Property<string>("ElementId");

                                                    b4.Property<int>("ElementType");

                                                    b4.Property<string>("Id");

                                                    b4.Property<string>("RegistryProviderId");

                                                    b4.Property<bool>("StrictMode");
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "HumanApproval", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.HumanApproval#HumanApprovalTaskConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Messaging", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.Messaging#MessagingTaskConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Topic");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.Property<string>("Version");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "SchemaBinding", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.Messaging#MessagingTaskConfigurationJsonModel.SchemaBinding#SchemaBindingJsonModel", b4 =>
                                                {
                                                    b4.Property<string>("ContractId");

                                                    b4.Property<string>("ContractKey");

                                                    b4.Property<string>("ContractVersion");

                                                    b4.Property<string>("ElementId");

                                                    b4.Property<int>("ElementType");

                                                    b4.Property<string>("Id");

                                                    b4.Property<string>("RegistryProviderId");

                                                    b4.Property<bool>("StrictMode");
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Plugin", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Configuration#TaskConfigurationEnvelopeJsonModel.Plugin#PluginTaskConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("PluginId");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.ExecutionCondition#ExecutionConditionJsonModel", b2 =>
                                {
                                    b2.Property<int>("Engine");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel.Dsl#DslConditionConfigurationJsonModel", b4 =>
                                                {
                                                    b4.Property<string>("Expression");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");
                                                });
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.RetryPolicy#RetryPolicyJsonModel", b2 =>
                                {
                                    b2.Property<int>("MaxRetries");

                                    b2.PrimitiveCollection<string>("RetryableErrorCodes");

                                    b2.Property<bool>("StopOnNonRetryableError");

                                    b2.Property<int>("StrategyType");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Fixed", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel.Fixed#FixedRetryStrategyJsonModel", b4 =>
                                                {
                                                    b4.Property<TimeSpan>("Delay");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");
                                                });
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel", b2 =>
                                {
                                    b2.Property<TimeSpan>("Timeout");

                                    b2.Property<int>("TimeoutBehavior");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutBehaviorPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Fail", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Fail#FailTimeoutBehaviorPolicyJsonModel", b4 =>
                                                {
                                                    b4.Property<string>("ErrorCode");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");
                                                });

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Reconcile", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel", b4 =>
                                                {
                                                    b4.Property<int>("OrchestrationAction");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel", b5 =>
                                                        {
                                                            b5.Property<int>("MaxRetries");

                                                            b5.PrimitiveCollection<string>("RetryableErrorCodes");

                                                            b5.Property<bool>("StopOnNonRetryableError");

                                                            b5.Property<int>("StrategyType");

                                                            b5.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel", b6 =>
                                                                {
                                                                    b6.Property<string>("Type")
                                                                        .HasJsonPropertyName("$type");

                                                                    b6.ComplexProperty(typeof(Dictionary<string, object>), "Fixed", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel.Fixed#FixedRetryStrategyJsonModel", b7 =>
                                                                        {
                                                                            b7.Property<TimeSpan>("Delay");

                                                                            b7.Property<string>("Type")
                                                                                .HasJsonPropertyName("$type");
                                                                        });
                                                                });
                                                        });
                                                });

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Wait", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Wait#WaitTimeoutBehaviorPolicyJsonModel", b4 =>
                                                {
                                                    b4.Property<int>("OrchestrationAction");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");

                                                    b4.Property<TimeSpan>("WaitingTime");
                                                });
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Transformation", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Transformation#TransformationDefinitionJsonModel", b2 =>
                                {
                                    b2.Property<int>("Engine");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationEnvelopeJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.CompensationDefinition#CompensationDefinitionJsonModel.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationEnvelopeJsonModel.Dsl#DslTransformationConfigurationJsonModel", b4 =>
                                                {
                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("$type");
                                                });
                                        });
                                });

                            b1.ToJson("CompensationDefinitionJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel", b1 =>
                        {
                            b1.Property<string>("Type")
                                .HasJsonPropertyName("$type");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Http", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.Http#HttpTaskConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<bool>("AllowSyncResponse");

                                    b2.Property<string>("BaseUrlVariableRef");

                                    b2.PrimitiveCollection<string>("ExpectedStatusCodes");

                                    b2.Property<string>("HeadersTemplateJson");

                                    b2.Property<string>("Method");

                                    b2.Property<string>("QueryTemplateJson");

                                    b2.Property<string>("RelativePath");

                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "SchemaBinding", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.Http#HttpTaskConfigurationJsonModel.SchemaBinding#SchemaBindingJsonModel", b3 =>
                                        {
                                            b3.Property<string>("ContractId");

                                            b3.Property<string>("ContractKey");

                                            b3.Property<string>("ContractVersion");

                                            b3.Property<string>("ElementId");

                                            b3.Property<int>("ElementType");

                                            b3.Property<string>("Id");

                                            b3.Property<string>("RegistryProviderId");

                                            b3.Property<bool>("StrictMode");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "HumanApproval", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.HumanApproval#HumanApprovalTaskConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Messaging", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.Messaging#MessagingTaskConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("Topic");

                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.Property<string>("Version");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "SchemaBinding", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.Messaging#MessagingTaskConfigurationJsonModel.SchemaBinding#SchemaBindingJsonModel", b3 =>
                                        {
                                            b3.Property<string>("ContractId");

                                            b3.Property<string>("ContractKey");

                                            b3.Property<string>("ContractVersion");

                                            b3.Property<string>("ElementId");

                                            b3.Property<int>("ElementType");

                                            b3.Property<string>("Id");

                                            b3.Property<string>("RegistryProviderId");

                                            b3.Property<bool>("StrictMode");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Plugin", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Configuration#TaskConfigurationEnvelopeJsonModel.Plugin#PluginTaskConfigurationJsonModel", b2 =>
                                {
                                    b2.Property<string>("PluginId");

                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");
                                });

                            b1.ToJson("ConfigurationJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExecutionCondition", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.ExecutionCondition#ExecutionConditionJsonModel.Configuration#ConditionConfigurationEnvelopeJsonModel.Dsl#DslConditionConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Expression");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("ExecutionConditionJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.RetryPolicy#RetryPolicyJsonModel", b1 =>
                        {
                            b1.Property<int>("MaxRetries");

                            b1.PrimitiveCollection<string>("RetryableErrorCodes");

                            b1.Property<bool>("StopOnNonRetryableError");

                            b1.Property<int>("StrategyType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Fixed", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel.Fixed#FixedRetryStrategyJsonModel", b3 =>
                                        {
                                            b3.Property<TimeSpan>("Delay");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("RetryPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel", b1 =>
                        {
                            b1.Property<TimeSpan>("Timeout");

                            b1.Property<int>("TimeoutBehavior");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TimeoutBehaviorPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Fail", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Fail#FailTimeoutBehaviorPolicyJsonModel", b3 =>
                                        {
                                            b3.Property<string>("ErrorCode");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Reconcile", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel", b3 =>
                                        {
                                            b3.Property<int>("OrchestrationAction");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.ComplexProperty(typeof(Dictionary<string, object>), "RetryPolicy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel", b4 =>
                                                {
                                                    b4.Property<int>("MaxRetries");

                                                    b4.PrimitiveCollection<string>("RetryableErrorCodes");

                                                    b4.Property<bool>("StopOnNonRetryableError");

                                                    b4.Property<int>("StrategyType");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "Strategy", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel", b5 =>
                                                        {
                                                            b5.Property<string>("Type")
                                                                .HasJsonPropertyName("$type");

                                                            b5.ComplexProperty(typeof(Dictionary<string, object>), "Fixed", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Reconcile#ReconcileTimeoutBehaviorPolicyJsonModel.RetryPolicy#RetryPolicyJsonModel.Strategy#RetryStrategyEnvelopeJsonModel.Fixed#FixedRetryStrategyJsonModel", b6 =>
                                                                {
                                                                    b6.Property<TimeSpan>("Delay");

                                                                    b6.Property<string>("Type")
                                                                        .HasJsonPropertyName("$type");
                                                                });
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Wait", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.TimeoutPolicy#TimeoutPolicyJsonModel.TimeoutBehaviorPolicy#TimeoutBehaviorPolicyEnvelopeJsonModel.Wait#WaitTimeoutBehaviorPolicyJsonModel", b3 =>
                                        {
                                            b3.Property<int>("OrchestrationAction");

                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");

                                            b3.Property<TimeSpan>("WaitingTime");
                                        });
                                });

                            b1.ToJson("TimeoutPolicyJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Transformation", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Transformation#TransformationDefinitionJsonModel", b1 =>
                        {
                            b1.Property<int>("Engine");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationEnvelopeJsonModel", b2 =>
                                {
                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Dsl", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TaskDefinitionEntity.Transformation#TransformationDefinitionJsonModel.Configuration#TransformationConfigurationEnvelopeJsonModel.Dsl#DslTransformationConfigurationJsonModel", b3 =>
                                        {
                                            b3.Property<string>("Type")
                                                .HasJsonPropertyName("$type");
                                        });
                                });

                            b1.ToJson("TransformationJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.HasIndex("StageDefinitionId", "Order");

                    b.ToTable("TaskDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TriggerChannel", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity.TriggerChannel#TriggerChannelEnvelopeJsonModel", b1 =>
                        {
                            b1.Property<string>("Type")
                                .HasJsonPropertyName("$type");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Event", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity.TriggerChannel#TriggerChannelEnvelopeJsonModel.Event#EventTriggerChannelJsonModel", b2 =>
                                {
                                    b2.Property<string>("Topic");

                                    b2.Property<string>("Type")
                                        .HasJsonPropertyName("$type");

                                    b2.Property<string>("Version");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "SchemaBinding", "Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.TriggerBindingEntity.TriggerChannel#TriggerChannelEnvelopeJsonModel.Event#EventTriggerChannelJsonModel.SchemaBinding#SchemaBindingJsonModel", b3 =>
                                        {
                                            b3.Property<string>("ContractId");

                                            b3.Property<string>("ContractKey");

                                            b3.Property<string>("ContractVersion");

                                            b3.Property<string>("ElementId");

                                            b3.Property<int>("ElementType");

                                            b3.Property<string>("Id");

                                            b3.Property<string>("RegistryProviderId");

                                            b3.Property<bool>("StrictMode");
                                        });
                                });

                            b1.ToJson("TriggerChannelJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.ToTable("TriggerBindings", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.VariableDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Key")
                        .IsUnique();

                    b.ToTable("VariableDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.OrchestrationDefinitionEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Design.Storage.SqlServer.Entities.DomainEntity", "DomainRef")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DomainRef");
                });
#pragma warning restore 612, 618
        }
    }
}
