<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <ProjectReference Include="..\..\src\Krackend.EventSourcing.Abstractions\Krackend.EventSourcing.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Krackend.EventSourcing.EntityFrameworkCore\Krackend.EventSourcing.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Krackend.EventSourcing\Krackend.EventSourcing.csproj" />
    <ProjectReference Include="..\..\src\Krackend.EventSourcing.Testing\Krackend.EventSourcing.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
