// <auto-generated />
using System;
using Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krackend.Sagas.Orchestrations.ControlPlaneHost.Sample.Migrations.ControlPlaneStorage
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260825194026_AddDesignRuntimeConnectionTokens")]
    partial class AddDesignRuntimeConnectionTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.BranchRuleDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConditionJson");

                    b.Property<byte[]>("FromId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("NavigateToId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("NavigateToType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("BranchRuleDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.DomainEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Domains", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.OrchestrationDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Domain")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("DomainId")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("OwnerTeamId")
                        .HasColumnType("binary(16)");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerTeamId");

                    b.ToTable("OrchestrationDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.OrchestrationVersionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationDefinitionId");

                    b.HasIndex("OrchestrationDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("OrchestrationVersions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.ParallelGroupDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("MaxParallelAgents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.ToTable("ParallelGroupDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.StageDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExecutionCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExecutionConditionJson");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Order");

                    b.ToTable("StageDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.TaskDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CompensationDefinition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompensationDefinitionJson");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConfigurationJson");

                    b.Property<string>("DispatchType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExecutionCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExecutionConditionJson");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OnErrorPolicy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("ParallelGroupId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("RetryPolicy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RetryPolicyJson");

                    b.Property<byte[]>("StageDefinitionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("TimeoutPolicy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TimeoutPolicyJson");

                    b.Property<string>("Transformation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransformationJson");

                    b.HasKey("Id");

                    b.HasIndex("StageDefinitionId");

                    b.HasIndex("StageDefinitionId", "Order");

                    b.ToTable("TaskDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.TriggerBindingEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("TriggerChannel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TriggerChannelJson");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.ToTable("TriggerBindings", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.VariableDefinitionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("OrchestrationVersionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId");

                    b.HasIndex("OrchestrationVersionId", "Key")
                        .IsUnique();

                    b.ToTable("VariableDefinitions", "Design");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ArtifactEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrchestrationDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrchestrationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEvent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId", "ArtifactType")
                        .IsUnique();

                    b.ToTable("Artifacts", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.EnvironmentEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Environments", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.OrchestrationAllowedRuntimeNodeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.HasIndex("OrchestrationDefinitionId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("OrchestrationAllowedRuntimeNodes", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseAttemptEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("ReleaseTargetId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTargetId");

                    b.ToTable("ReleaseAttempts", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("OrchestrationDefinitionId");

                    b.ToTable("Releases", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleasePlanTargetEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.HasIndex("ReleaseId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("ReleasePlanTargets", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseTargetEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActivationStatus")
                        .HasColumnType("int");

                    b.Property<byte[]>("ArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("ReleaseId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("RolloutGroup")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("RuntimeVersionApplied")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("ReleaseTargets", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("RuntimeCapabilities", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("AccessTokenTtlSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("int");

                    b.Property<string>("EndpointApiPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EndpointBaseUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<byte[]>("EnvironmentId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("InboundAllowedScopes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("InboundClientId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("InboundCredentialCreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundCredentialRevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundCredentialRotatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InboundCredentialStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InboundKeyId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InboundLastFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("InboundLastTokenFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundLastTokenIssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InboundSecretHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OutboundClientId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OutboundCredentialImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundCredentialStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OutboundKeyId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OutboundLastTokenReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundRequestedScopes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ProtectedOutboundSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TokenRefreshSkewSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TokenValidationCacheTtlSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("InboundClientId")
                        .IsUnique()
                        .HasFilter("[InboundClientId] IS NOT NULL AND [InboundClientId] <> ''");

                    b.ToTable("RuntimeNodes", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Teams", "Security");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamMemberEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("TeamId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("TeamMembers", "Security");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.OrchestrationDefinitionEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Design.Entities.DomainEntity", "DomainRef")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamEntity", "OwnerTeamRef")
                        .WithMany()
                        .HasForeignKey("OwnerTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DomainRef");

                    b.Navigation("OwnerTeamRef");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.OrchestrationAllowedRuntimeNodeEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseAttemptEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseTargetEntity", "ReleaseTarget")
                        .WithMany("Attempts")
                        .HasForeignKey("ReleaseTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTarget");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleasePlanTargetEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseEntity", "Release")
                        .WithMany("Targets")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseTargetEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseEntity", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Release");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany("Capabilities")
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.EnvironmentEntity", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamMemberEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseEntity", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.ReleaseTargetEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Distribution.Entities.RuntimeNodeEntity", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.ControlPlane.Storage.EntityFramework.Security.Entities.TeamEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
