<Project>
  <PropertyGroup>
    <TurtlePathVersion>1.6.3</TurtlePathVersion>
    <TurtlePathVersion Condition="'$(TurtlePathVersion)' == 'TURTLEPATH_&#x56;ERSION'">1.6.3</TurtlePathVersion>
  </PropertyGroup>

	<ItemGroup>
    <PackageReference Update="Scalar.AspNetCore" Version="2.16.18"/>
    <PackageReference Update="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Update="Pelican.Mediator" Version="2.0.0" />
    <PackageReference Update="Pigeon.Messaging" Version="2.8.0" />
    <PackageReference Update="Pigeon.Messaging.Azure.ServiceBus" Version="2.8.0" />
    <PackageReference Update="Pigeon.Messaging.Outbox.EntityFrameworkCore" Version="2.8.0" />
    <PackageReference Update="Pigeon.Messaging.Rabbit" Version="2.8.0" />
    <PackageReference Update="Krackend.EventSourcing.EntityFrameworkCore" Version="1.2.1" />
    <PackageReference Update="Spider.Pipelines" Version="2.1.0" />
    <PackageReference Update="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Update="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Update="Crabalidator" Version="1.0.4" />
    <PackageReference Update="OctoMap" Version="1.1.1" />
    <PackageReference Update="OctoMap.Analyzers" Version="1.1.1" />
    <PackageReference Update="Ulid" Version="1.4.1" />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10"/>
	<PackageReference Update="Asp.Versioning.Mvc" Version="10.2.1" />
	<PackageReference Update="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Update="TurtlePath" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Abstractions" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Analyzers" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Automations" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Crabalidator" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.DataScorpio" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Domain" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.EntityFrameworkCore" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.EventSourcing" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.ExceptionHandling.Consumers" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.ExceptionHandling" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.ExceptionHandling.AspNetCore" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.ExceptionHandling.Workers" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Jobs" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.OctoMap" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Spider" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Spider.Transactions" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Testing" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Testing.EntityFrameworkCore" Version="$(TurtlePathVersion)" />
    <PackageReference Update="TurtlePath.Testing.Integration" Version="$(TurtlePathVersion)" />
  </ItemGroup>

</Project>
