<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Krackend.Sagas.Orchestrations.Abstractions</PackageId>
    <Description>Krackend.Sagas.Orchestrations.Abstractions provides shared contracts and primitives for saga orchestration runtimes.</Description>
    <PackageTags>saga;orchestration;contracts;distributed;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ulid" />
  </ItemGroup>

</Project>
