<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pigeon.Messaging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Krackend.Sagas.Orchestrations.Runtime\Krackend.Sagas.Orchestrations.Runtime.csproj" />
  </ItemGroup>

</Project>
