// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Infrastructure;

#nullable disable

namespace Krackend.Sagas.Orchestrations.ControlPlaneHost.Sample.Migrations.DistributionStorage
{
    [DbContext(typeof(DistributionStorageDbContext))]
    [Migration("20260518224520_InitialDistributionStorageSqlServer")]
    partial class InitialDistributionStorageSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactReleaseEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrchestrationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrchestrationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationId", "OrchestrationVersion", "ArtifactType")
                        .IsUnique();

                    b.ToTable("DistributionArtifactReleases", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAssignmentEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActivationStatus")
                        .HasColumnType("int");

                    b.Property<byte[]>("ArtifactReleaseId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("PromotionId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("RolloutGroup")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("RuntimeVersionApplied")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactReleaseId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("DistributionAssignments", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAttemptEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("DistributionAssignmentId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DistributionAssignmentId");

                    b.ToTable("DistributionAttempts", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ArtifactReleaseId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactReleaseId");

                    b.ToTable("DistributionPromotions", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionTargetEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("PromotionId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.HasIndex("PromotionId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("DistributionPromotionTargets", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("DistributionRuntimeCapabilities", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ApiKeyReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AuthenticationMode")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("int");

                    b.Property<string>("EndpointApiPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EndpointBaseUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DistributionRuntimeNodes", (string)null);
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAssignmentEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactReleaseEntity", "ArtifactRelease")
                        .WithMany()
                        .HasForeignKey("ArtifactReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionEntity", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtifactRelease");

                    b.Navigation("Promotion");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAttemptEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAssignmentEntity", "DistributionAssignment")
                        .WithMany("Attempts")
                        .HasForeignKey("DistributionAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionAssignment");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactReleaseEntity", "ArtifactRelease")
                        .WithMany()
                        .HasForeignKey("ArtifactReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtifactRelease");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionTargetEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionEntity", "Promotion")
                        .WithMany("Targets")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany("Capabilities")
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.DistributionAssignmentEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.PromotionEntity", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
