// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Infrastructure;

#nullable disable

namespace Krackend.Sagas.Orchestrations.ControlPlaneHost.Sample.Migrations.DistributionStorage
{
    [DbContext(typeof(DistributionStorageDbContext))]
    [Migration("20260522030218_DistributionSchemaNamespace")]
    partial class DistributionSchemaNamespace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Distribution")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrchestrationDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrchestrationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEvent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationVersionId", "ArtifactType")
                        .IsUnique();

                    b.ToTable("Artifacts", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.OrchestrationProjectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.ToTable("Orchestrations", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.OrchestrationAllowedRuntimeNodeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.HasIndex("OrchestrationDefinitionId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("OrchestrationAllowedRuntimeNodes", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseAttemptEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("ReleaseTargetId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTargetId");

                    b.ToTable("ReleaseAttempts", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrchestrationDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("OrchestrationDefinitionId");

                    b.ToTable("Releases", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleasePlanTargetEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.HasIndex("ReleaseId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("ReleasePlanTargets", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseTargetEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActivationStatus")
                        .HasColumnType("int");

                    b.Property<byte[]>("ArtifactId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("ReleaseId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("RolloutGroup")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("RuntimeVersionApplied")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("ReleaseTargets", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RuntimeNodeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeNodeId");

                    b.ToTable("RuntimeCapabilities", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ApiKeyReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AuthenticationMode")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("int");

                    b.Property<string>("EndpointApiPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EndpointBaseUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RuntimeNodes", "Distribution");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.OrchestrationAllowedRuntimeNodeEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.OrchestrationProjectionEntity", "Orchestration")
                        .WithMany("AllowedRuntimeNodes")
                        .HasForeignKey("OrchestrationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orchestration");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseAttemptEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseTargetEntity", "ReleaseTarget")
                        .WithMany("Attempts")
                        .HasForeignKey("ReleaseTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTarget");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleasePlanTargetEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseEntity", "Release")
                        .WithMany("Targets")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseTargetEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseEntity", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany()
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Release");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeCapabilityEntity", b =>
                {
                    b.HasOne("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", "RuntimeNode")
                        .WithMany("Capabilities")
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.OrchestrationProjectionEntity", b =>
                {
                    b.Navigation("AllowedRuntimeNodes");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseEntity", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.ReleaseTargetEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Krackend.Sagas.Orchestrations.Distribution.Storage.SqlServer.Entities.RuntimeNodeEntity", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}

